services:
  mysql:
    image: mysql:8.0
    container_name: adminlte_bd_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: adminlte_bd
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
